### ISSUE TITLE
Here Map Premium sdk with SwiftUi

### ISSUE THREAD

**Issue by bdushi** [heremaps/here-ios-sdk-examples#153] opened 2020-01-21 12:43 UTC
I ma try to use Here Map Premium sdk with SwiftUi, but I get this error: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

**Comment by bdushi** [comment] 2020-01-27 08:49
https://stackoverflow.com/questions/58870090/heremaps-with-swiftui-crashes-with-exc-bad-instruction-upon-instantiation

**Comment by starand** [comment] 2020-02-17 09:04
https://stackoverflow.com/a/59942718/6866440

**Comment by bdushi** [comment] 2020-02-17 10:26
No, this did not halp me, I am try to create an Instance of HereMap Premium Sdk using SwiftUi not through StroyBoard: NMAMapView mapView = NMAMapView(frame: self.view.frame)

**Comment by dashchak** [comment] 2020-02-17 16:14
Hi, @bdushi 
Indeed, issue is reproduced with latest NMAKit. Starting investigation.

Thanks for reporting!

**Comment by dashchak** [comment] 2020-02-17 16:49
I have found the root cause. Fix will be included in next HERE SDK Release(3.15) which is planned on April 1, 2020.

**Closed** 2020-03-10 11:17 UTC
