### ISSUE TITLE
iOS 13 - Crash when creating a NMAMapView

### ISSUE THREAD

**Issue by AgDP** [heremaps/here-ios-sdk-examples#121] opened 2019-09-12 11:29 UTC
Hi!

I have an error using NMAMapView in iOS 13.

![Captura de pantalla 2019-09-12 a las 13 24 41](https://user-images.githubusercontent.com/9484476/64780609-1e652580-d561-11e9-835b-96dad5b9eab5.png)

This error happens only in iOS 13. The crash occurs in the simulator.
In iOS 12 or 11 it works correctly.
The version is "HEREMaps 3.12.2"

**Comment by dashchak** [comment] 2019-09-13 16:55
I can not reproduce the crash in MapEngineinitializationApp Swift sample app on iPhone 11 Pro Simulator running iOS 13 for NMAKit 3.12.2.
Have you run "pod install" or added NMAKit manually?
Have you edited any default Xcode setting for MapEngineinitializationApp scheme?

**Comment by dashchak** [comment] 2019-09-16 15:38
It is reproducible when project is run on Simulator with non-english System language. 
As a workaround try to reset Simulator, then change Mac OS system language to English and run your app.

**Comment by AgDP** [comment] 2019-09-16 18:54
Hi!
I put the OS in English and executed the sample project on simulator. I have this error in case it can help you:

`2019-09-16 20:45:59.666821+0200 MapEngineinitializationApp[4700:86714] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-09-16 20:45:59.666925+0200 MapEngineinitializationApp[4700:86842] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}`

Same error in my project.

Regards

**Comment by dashchak** [comment] 2019-09-17 07:50
Try this solution: https://stackoverflow.com/a/54692253/5940721

**Comment by dashchak** [comment] 2019-09-19 09:48
The crash will be fixed starting from HEREMaps 3.13. Thanks for reporting the issue!

The root cause was in iOS behavioral change between 12 and 13 Simulators with non-English locale.

If you run:
 `NSString *countryCode = [[NSLocale currentLocale] objectForKey:NSLocaleCountryCode]`
For some reason it returns **nil** in iOS 13 and actual value in iOS 12. We use country code to set geopolitical map view.

**Comment by AgDP** [comment] 2019-09-19 12:16
Perfect!
Thanks for your work!

**Comment by buttifabio** [comment] 2019-10-24 12:59
> The crash will be fixed starting from HEREMaps 3.13. Thanks for reporting the issue!

@dashchak is there a release date for HEREMaps 3.13?

**Comment by starand** [comment] 2019-10-24 13:01
@buttifabio 3.13 SP1 should be released on Monday.

**Comment by buttifabio** [comment] 2019-10-29 11:18
The last release of HEREMapsUI (2.1.2) has HEREMaps 3.12.2 dependency.
I'm using CocoaPods and if I try with `pod update HEREMaps` to 3.13 it gives me an error because HEREMapsUI still depends from 3.12.2.

Do I need to wait for the next release of HEREMapsUI?

**Comment by datasun** [comment] 2019-10-29 11:37
Yes, HEREMapsUI (MSDKUI) still depends on 3.12. please wait for the next release. Integration is not public yet, once available it will be announced on the [MSDUI release page](https://github.com/heremaps/msdkui-android/releases).

**Comment by Azat92** [comment] 2019-12-09 15:19
Hi, I'm using version 3.13.3 and still have this crash, even on iOS 12. Since issue is closed, does it mean that it was fixed?

**Comment by dashchak** [comment] 2019-12-09 15:42
@Azat92 The Simulator locale crash issue should be fixed in 3.13.3. 
Probably you found different one. Please specify more details.

**Comment by Azat92** [comment] 2019-12-10 06:36
@dashchak I'm not sure what MSDKUI is. I am using cocoapods with pod HEREMaps. From time to time I see the crash on a line where I initialize a NMAMapView, exact the same as here on top of the thread. Last time I got this crash during debugging session on iPhone XS Max running iOS 12.4

**Comment by datasun** [comment] 2019-12-10 08:26
@Azat92 [MSDKUI](https://github.com/heremaps/here-ios-sdk-examples/issues/121#issuecomment-563887910) is an open source framework that offers pre-built UIs on top of HereMaps / HERE SDK for iOS (Premium). So, it seems the crash is not related to this framework. This should help to narrow this down. Thanks for sharing. 

We can reopen this issue if we know better if this is a new issue or a regression. It would also help if you can provide more details on the steps to reproduce. Thanks.

**Closed** 2019-12-10 08:26 UTC

**Comment by dashchak** [comment] 2019-12-10 08:49
@Azat92 Please open new issue with crash details or steps to reproduce attached. As current one related only to crash on iOS 13 Simulator. 
Thanks!
