### ISSUE TITLE
Crashes on SwiftUI previews iOS 14.5

### ISSUE THREAD

**Issue by CristiHabliuc** [heremaps/here-ios-sdk-examples#215] opened 2021-08-29 09:15 UTC
**Describe the bug**
Running the example project for SwiftUI crashes on preview on iOS 14.5 SDK, can't get the map to work with SwiftUI at all. I tried it on my app with no success, then downloaded the example project and the same thing happens.

**Steps To Reproduce**
1. Download the latest examples from this repo
2. Run `pod install` in the SwitUIApp project folder
3. Open workspace
4. Go to `ContentView` and try to preview
5. It crashes the preview

Relevant crashlog extract:
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
CoreSimulator 775 - Device: iPhone 11 (832310E5-2146-43A9-AC3C-7FEA0FB5D364) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 11

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6030992e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff603435bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff200fbcb5 abort + 120
3   com.here.sdk                  	0x0000000107fcc555 shouldWait1() + 351
4   com.here.sdk                  	0x00000001080765f4 0x107f63000 + 1127924
5   com.here.sdk                  	0x0000000108076338 0x107f63000 + 1127224
6   nma.iOSHereSDKSamples.SwiftUI 	0x0000000107e0574d @nonobjc NMAMapView.init(frame:) + 77
7   nma.iOSHereSDKSamples.SwiftUI 	0x0000000107e02a4a NMAMapView.__allocating_init(frame:) + 74
8   nma.iOSHereSDKSamples.SwiftUI 	0x0000000107e04294 HEREMapsView.init(stateModel:mapScheme:) + 228 (HEREMapsView.swift:19)
...
```

**Expected behavior**
The map should load and obviously not crash

**Smartphone (please complete the following information):**
 - Device: Simulator, XCode Preview
 - XCode Version: 12.5.1
 - OS: iOS 14.5
 - SDK Version: 3.18.3

**Comment by dashchak** [comment] 2021-08-31 14:43
hi @CristiHabliuc, 
Our QA team is not able to reproduce the crash. 
Please make sure you entered valid HERE credentials in AppDelegate.swift and matching bundle id of your app.
Does crash occur on real device?

**Comment by dashchak** [comment] 2021-09-06 11:39
@CristiHabliuc any updates on the issue?
Can we close it?

**Closed** 2021-09-13 16:11 UTC
