### ISSUE TITLE
HEREMaps crashes using SwiftUI on device rotation

### ISSUE THREAD

**Issue by fahlout** [heremaps/here-ios-sdk-examples#170] opened 2020-07-02 14:58 UTC
I have created a SwiftUI view for NMAMapView using UIViewRepresentable, but when I rotate the device it crashes with the following error:

```
2020-07-02 09:53:14.865018-0500 HEREMapsSwiftUI[1027:520096] [tcp] tcp_input [C1.1:3] flags=[R] seq=2783000016, ack=0, win=0 state=CLOSED rcv_nxt=2783000016, snd_una=3650507250
-[MTLDebugDevice newTextureWithDescriptor:iosurface:plane:]:1806: failed assertion `Texture Descriptor Validation
IOSurface textures must use MTLStorageModeShared
'
2020-07-02 09:55:03.582208-0500 HEREMapsSwiftUI[1027:520877] -[MTLDebugDevice newTextureWithDescriptor:iosurface:plane:], line 1806: error 'Texture Descriptor Validation
IOSurface textures must use MTLStorageModeShared
'
-[MTLDebugDevice newTextureWithDescriptor:iosurface:plane:]:1806: failed assertion `Texture Descriptor Validation
IOSurface textures must use MTLStorageModeShared
'
```

The code I used to represent NMAMapView in SwiftUI:

```swift
import SwiftUI
import NMAKit

struct HEREMap: UIViewRepresentable {
    func makeUIView(context: Context) -> NMAMapView {
        let mapView = NMAMapView()
        mapView.copyrightLogoPosition = .bottomLeft
        mapView.zoomLevel = 13.2
        mapView.set(geoCenter: NMAGeoCoordinates(latitude: 49.258867, longitude: -123.008046),
        animation: .linear)
        return mapView
    }
    
    func updateUIView(_ uiView: NMAMapView, context: Context) {}
}
```

**Comment by dashchak** [comment] 2020-07-02 15:37
Could you please specify HERE SDK and iOS versions?

**Comment by fahlout** [comment] 2020-07-02 15:50
HERE SDK FOR IOS (PREMIUM EDITION)

I have tried it in both iOS 13 and using the iOS 14 Beta in conjunction with the beta version of Xcode 12. It works in iOS 13, but crashes in iOS 14.

I know iOS 14 is not yet supported by the HERE SDK, but I wanted to make you guys aware of the issue and hope for it to be fixed by time iOS 14 releases this Fall.

**Comment by dashchak** [comment] 2020-07-02 18:03
Thanks for reporting. 
We have just started iOS 14 investigation. Full iOS 14 support is planned in 3.17 version this Fall.

**Comment by lakersr8ers** [comment] 2020-07-30 04:33
Any update on this issue? Also experiencing this issue.

**Comment by dashchak** [comment] 2020-07-30 08:02
iOS 14 issue will be fixed in HERE SDK 3.17 which is planned to be released in the middle of October 2020. Also, we plan to migrate to full Metal support in this version. 
Stay tuned. Thanks!

**Comment by lakersr8ers** [comment] 2020-07-30 16:06
Is October not too late? Current experience is the app crashes, every time I launch a view with NMAMap. Apple typically launches their new OS to customers in September. Wouldn't that mean that for a month customers who use HEREMaps on iOS 14 would be experiencing crashes? Ideally this would come out sooner so we can give it some bake time. Love HEREMaps, but also don't want to subject our customers to crashes.

**Comment by dashchak** [comment] 2020-09-15 11:35
Looks like the issue is not reproduced anymore in HERE SDK 3.16 with latest Xcode 12 beta 6 and iOS 14 beta 8. 
Check out our [SwiftUI sample](https://github.com/heremaps/here-ios-sdk-examples/tree/master/swiftui-ios-swift)

Meanwhile 3.17 version is migrated to full Metal support and is being actively verified internally.

**Comment by fahlout** [comment] 2020-09-17 21:31
Based on the sample I can confirm the issue seems to have been resolved. 

Do you have a rough idea on when 3.17 might be released since iOS 14 has been released?

**Comment by dashchak** [comment] 2020-09-21 11:17
Due too significant changes in OpenGL -> Metal migration, we decided to reserve some time to make rendering mature. Instead of October 1st, we expect it on October 15th.

**Comment by dashchak** [comment] 2020-10-19 09:49
@fahlout 
3.17 Release date is postponed at least to October 30th.

**Closed** 2021-07-07 09:38 UTC
