### ISSUE TITLE
Zoom level issue in turn by turn navigation

### ISSUE THREAD

**Issue by munish-techindustan** [heremaps/here-ios-sdk-examples#159] opened 2020-03-06 13:18 UTC
I have set **mapTrackingAutoZoomEnabled** to false and set zoom level to 18 when start navigation by using: 
mapView.set(zoomLevel: 18, animation: .none)

Sometimes it's working as expected but in some cases it's not working. It automatically set the Zoom level to 14-17 but it still displays that the Zoom level is 18.

**Comment by dashchak** [comment] 2020-03-10 09:53
Could you please provide more details in order to reproduce the issue. 
Do you pause/resume navigation or go to background/foreground? Is **mapTrackingEnabled** set to true? What version of HERE SDK is used?

**Comment by dashchak** [comment] 2020-03-10 11:25
Indeed, issue is reproduced when during navigation map is swiped and current position is not visible.
Will be fixed in HERE SDK 3.15, which is planned to be released on Apr 1, 2020.
Thanks for reporting!

**Comment by dashchak** [comment] 2020-04-14 09:30
Hi, @munish-techindustan 
Could you please upgrade to HERE SDK 3.15 and verify the issue is fixed?

**Comment by munish-techindustan** [comment] 2020-04-14 14:15
Hello @dashchak, I am unable to upgrade to HERE SDK to 3.15. I am using 'HEREMapsUI'. Can you please let me know how to upgrade 'HEREMapsUI' in which HERE SDK 3.15.
Thanks.

**Comment by dashchak** [comment] 2020-04-14 14:48
In this case you will need to wait for next [HEREMapsUI release](https://github.com/heremaps/msdkui-ios/releases).

**Comment by arunmt024** [comment] 2021-06-03 12:23
@dashchak  Any idea about how to pause and resume work while we are navigation.

**Comment by dashchak** [comment] 2021-06-07 10:11
Hi @arunmt024, 
You can pause/resume navigation by using [paused](https://developer.here.com/documentation/ios-premium/3.18/api_reference_jazzy/Classes/NMANavigationManager.html#%2Fc:objc(cs)NMANavigationManager(py)paused) property of NMANavigationManager.

Please start a new thread in case of any issues.

**Closed by dashchak** 2021-06-07 10:11 UTC
